// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package com.moosd.kitchensync;

public final class Message {
  private Message() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface PacketOrBuilder extends
      // @@protoc_insertion_point(interface_extends:message.Packet)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>required int32 id = 1;</code>
     */
    int getId();

    /**
     * <code>repeated .message.Packet.EchoPacket ep = 2;</code>
     */
    java.util.List<com.moosd.kitchensync.Message.Packet.EchoPacket> 
        getEpList();
    /**
     * <code>repeated .message.Packet.EchoPacket ep = 2;</code>
     */
    com.moosd.kitchensync.Message.Packet.EchoPacket getEp(int index);
    /**
     * <code>repeated .message.Packet.EchoPacket ep = 2;</code>
     */
    int getEpCount();
    /**
     * <code>repeated .message.Packet.EchoPacket ep = 2;</code>
     */
    java.util.List<? extends com.moosd.kitchensync.Message.Packet.EchoPacketOrBuilder> 
        getEpOrBuilderList();
    /**
     * <code>repeated .message.Packet.EchoPacket ep = 2;</code>
     */
    com.moosd.kitchensync.Message.Packet.EchoPacketOrBuilder getEpOrBuilder(
        int index);

    /**
     * <code>repeated .message.Packet.BrowserPacket bp = 3;</code>
     */
    java.util.List<com.moosd.kitchensync.Message.Packet.BrowserPacket> 
        getBpList();
    /**
     * <code>repeated .message.Packet.BrowserPacket bp = 3;</code>
     */
    com.moosd.kitchensync.Message.Packet.BrowserPacket getBp(int index);
    /**
     * <code>repeated .message.Packet.BrowserPacket bp = 3;</code>
     */
    int getBpCount();
    /**
     * <code>repeated .message.Packet.BrowserPacket bp = 3;</code>
     */
    java.util.List<? extends com.moosd.kitchensync.Message.Packet.BrowserPacketOrBuilder> 
        getBpOrBuilderList();
    /**
     * <code>repeated .message.Packet.BrowserPacket bp = 3;</code>
     */
    com.moosd.kitchensync.Message.Packet.BrowserPacketOrBuilder getBpOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code message.Packet}
   */
  public static final class Packet extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:message.Packet)
      PacketOrBuilder {
    // Use Packet.newBuilder() to construct.
    private Packet(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Packet(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Packet defaultInstance;
    public static Packet getDefaultInstance() {
      return defaultInstance;
    }

    public Packet getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Packet(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt32();
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                ep_ = new java.util.ArrayList<com.moosd.kitchensync.Message.Packet.EchoPacket>();
                mutable_bitField0_ |= 0x00000002;
              }
              ep_.add(input.readMessage(com.moosd.kitchensync.Message.Packet.EchoPacket.PARSER, extensionRegistry));
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                bp_ = new java.util.ArrayList<com.moosd.kitchensync.Message.Packet.BrowserPacket>();
                mutable_bitField0_ |= 0x00000004;
              }
              bp_.add(input.readMessage(com.moosd.kitchensync.Message.Packet.BrowserPacket.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          ep_ = java.util.Collections.unmodifiableList(ep_);
        }
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          bp_ = java.util.Collections.unmodifiableList(bp_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.moosd.kitchensync.Message.internal_static_message_Packet_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.moosd.kitchensync.Message.internal_static_message_Packet_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.moosd.kitchensync.Message.Packet.class, com.moosd.kitchensync.Message.Packet.Builder.class);
    }

    public static com.google.protobuf.Parser<Packet> PARSER =
        new com.google.protobuf.AbstractParser<Packet>() {
      public Packet parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Packet(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Packet> getParserForType() {
      return PARSER;
    }

    public interface EchoPacketOrBuilder extends
        // @@protoc_insertion_point(interface_extends:message.Packet.EchoPacket)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>required string text = 1;</code>
       */
      boolean hasText();
      /**
       * <code>required string text = 1;</code>
       */
      java.lang.String getText();
      /**
       * <code>required string text = 1;</code>
       */
      com.google.protobuf.ByteString
          getTextBytes();
    }
    /**
     * Protobuf type {@code message.Packet.EchoPacket}
     */
    public static final class EchoPacket extends
        com.google.protobuf.GeneratedMessage implements
        // @@protoc_insertion_point(message_implements:message.Packet.EchoPacket)
        EchoPacketOrBuilder {
      // Use EchoPacket.newBuilder() to construct.
      private EchoPacket(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private EchoPacket(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final EchoPacket defaultInstance;
      public static EchoPacket getDefaultInstance() {
        return defaultInstance;
      }

      public EchoPacket getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private EchoPacket(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000001;
                text_ = bs;
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.moosd.kitchensync.Message.internal_static_message_Packet_EchoPacket_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.moosd.kitchensync.Message.internal_static_message_Packet_EchoPacket_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.moosd.kitchensync.Message.Packet.EchoPacket.class, com.moosd.kitchensync.Message.Packet.EchoPacket.Builder.class);
      }

      public static com.google.protobuf.Parser<EchoPacket> PARSER =
          new com.google.protobuf.AbstractParser<EchoPacket>() {
        public EchoPacket parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new EchoPacket(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<EchoPacket> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      public static final int TEXT_FIELD_NUMBER = 1;
      private java.lang.Object text_;
      /**
       * <code>required string text = 1;</code>
       */
      public boolean hasText() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string text = 1;</code>
       */
      public java.lang.String getText() {
        java.lang.Object ref = text_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            text_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string text = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTextBytes() {
        java.lang.Object ref = text_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          text_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private void initFields() {
        text_ = "";
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        if (!hasText()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeBytes(1, getTextBytes());
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(1, getTextBytes());
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static com.moosd.kitchensync.Message.Packet.EchoPacket parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.moosd.kitchensync.Message.Packet.EchoPacket parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.moosd.kitchensync.Message.Packet.EchoPacket parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.moosd.kitchensync.Message.Packet.EchoPacket parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.moosd.kitchensync.Message.Packet.EchoPacket parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.moosd.kitchensync.Message.Packet.EchoPacket parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static com.moosd.kitchensync.Message.Packet.EchoPacket parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static com.moosd.kitchensync.Message.Packet.EchoPacket parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static com.moosd.kitchensync.Message.Packet.EchoPacket parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.moosd.kitchensync.Message.Packet.EchoPacket parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(com.moosd.kitchensync.Message.Packet.EchoPacket prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code message.Packet.EchoPacket}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:message.Packet.EchoPacket)
          com.moosd.kitchensync.Message.Packet.EchoPacketOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.moosd.kitchensync.Message.internal_static_message_Packet_EchoPacket_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.moosd.kitchensync.Message.internal_static_message_Packet_EchoPacket_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.moosd.kitchensync.Message.Packet.EchoPacket.class, com.moosd.kitchensync.Message.Packet.EchoPacket.Builder.class);
        }

        // Construct using com.moosd.kitchensync.Message.Packet.EchoPacket.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          text_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.moosd.kitchensync.Message.internal_static_message_Packet_EchoPacket_descriptor;
        }

        public com.moosd.kitchensync.Message.Packet.EchoPacket getDefaultInstanceForType() {
          return com.moosd.kitchensync.Message.Packet.EchoPacket.getDefaultInstance();
        }

        public com.moosd.kitchensync.Message.Packet.EchoPacket build() {
          com.moosd.kitchensync.Message.Packet.EchoPacket result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public com.moosd.kitchensync.Message.Packet.EchoPacket buildPartial() {
          com.moosd.kitchensync.Message.Packet.EchoPacket result = new com.moosd.kitchensync.Message.Packet.EchoPacket(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.text_ = text_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.moosd.kitchensync.Message.Packet.EchoPacket) {
            return mergeFrom((com.moosd.kitchensync.Message.Packet.EchoPacket)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.moosd.kitchensync.Message.Packet.EchoPacket other) {
          if (other == com.moosd.kitchensync.Message.Packet.EchoPacket.getDefaultInstance()) return this;
          if (other.hasText()) {
            bitField0_ |= 0x00000001;
            text_ = other.text_;
            onChanged();
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          if (!hasText()) {
            
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.moosd.kitchensync.Message.Packet.EchoPacket parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.moosd.kitchensync.Message.Packet.EchoPacket) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private java.lang.Object text_ = "";
        /**
         * <code>required string text = 1;</code>
         */
        public boolean hasText() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required string text = 1;</code>
         */
        public java.lang.String getText() {
          java.lang.Object ref = text_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              text_ = s;
            }
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>required string text = 1;</code>
         */
        public com.google.protobuf.ByteString
            getTextBytes() {
          java.lang.Object ref = text_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            text_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string text = 1;</code>
         */
        public Builder setText(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          text_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string text = 1;</code>
         */
        public Builder clearText() {
          bitField0_ = (bitField0_ & ~0x00000001);
          text_ = getDefaultInstance().getText();
          onChanged();
          return this;
        }
        /**
         * <code>required string text = 1;</code>
         */
        public Builder setTextBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          text_ = value;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:message.Packet.EchoPacket)
      }

      static {
        defaultInstance = new EchoPacket(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:message.Packet.EchoPacket)
    }

    public interface BrowserPacketOrBuilder extends
        // @@protoc_insertion_point(interface_extends:message.Packet.BrowserPacket)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>required .message.Packet.BrowserPacket.UriType type = 1;</code>
       */
      boolean hasType();
      /**
       * <code>required .message.Packet.BrowserPacket.UriType type = 1;</code>
       */
      com.moosd.kitchensync.Message.Packet.BrowserPacket.UriType getType();

      /**
       * <code>required string uri = 2;</code>
       */
      boolean hasUri();
      /**
       * <code>required string uri = 2;</code>
       */
      java.lang.String getUri();
      /**
       * <code>required string uri = 2;</code>
       */
      com.google.protobuf.ByteString
          getUriBytes();
    }
    /**
     * Protobuf type {@code message.Packet.BrowserPacket}
     */
    public static final class BrowserPacket extends
        com.google.protobuf.GeneratedMessage implements
        // @@protoc_insertion_point(message_implements:message.Packet.BrowserPacket)
        BrowserPacketOrBuilder {
      // Use BrowserPacket.newBuilder() to construct.
      private BrowserPacket(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private BrowserPacket(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final BrowserPacket defaultInstance;
      public static BrowserPacket getDefaultInstance() {
        return defaultInstance;
      }

      public BrowserPacket getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private BrowserPacket(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 8: {
                int rawValue = input.readEnum();
                com.moosd.kitchensync.Message.Packet.BrowserPacket.UriType value = com.moosd.kitchensync.Message.Packet.BrowserPacket.UriType.valueOf(rawValue);
                if (value == null) {
                  unknownFields.mergeVarintField(1, rawValue);
                } else {
                  bitField0_ |= 0x00000001;
                  type_ = value;
                }
                break;
              }
              case 18: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000002;
                uri_ = bs;
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.moosd.kitchensync.Message.internal_static_message_Packet_BrowserPacket_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.moosd.kitchensync.Message.internal_static_message_Packet_BrowserPacket_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.moosd.kitchensync.Message.Packet.BrowserPacket.class, com.moosd.kitchensync.Message.Packet.BrowserPacket.Builder.class);
      }

      public static com.google.protobuf.Parser<BrowserPacket> PARSER =
          new com.google.protobuf.AbstractParser<BrowserPacket>() {
        public BrowserPacket parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new BrowserPacket(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<BrowserPacket> getParserForType() {
        return PARSER;
      }

      /**
       * Protobuf enum {@code message.Packet.BrowserPacket.UriType}
       */
      public enum UriType
          implements com.google.protobuf.ProtocolMessageEnum {
        /**
         * <code>URL = 0;</code>
         */
        URL(0, 0),
        /**
         * <code>TELEPHONE = 1;</code>
         */
        TELEPHONE(1, 1),
        ;

        /**
         * <code>URL = 0;</code>
         */
        public static final int URL_VALUE = 0;
        /**
         * <code>TELEPHONE = 1;</code>
         */
        public static final int TELEPHONE_VALUE = 1;


        public final int getNumber() { return value; }

        public static UriType valueOf(int value) {
          switch (value) {
            case 0: return URL;
            case 1: return TELEPHONE;
            default: return null;
          }
        }

        public static com.google.protobuf.Internal.EnumLiteMap<UriType>
            internalGetValueMap() {
          return internalValueMap;
        }
        private static com.google.protobuf.Internal.EnumLiteMap<UriType>
            internalValueMap =
              new com.google.protobuf.Internal.EnumLiteMap<UriType>() {
                public UriType findValueByNumber(int number) {
                  return UriType.valueOf(number);
                }
              };

        public final com.google.protobuf.Descriptors.EnumValueDescriptor
            getValueDescriptor() {
          return getDescriptor().getValues().get(index);
        }
        public final com.google.protobuf.Descriptors.EnumDescriptor
            getDescriptorForType() {
          return getDescriptor();
        }
        public static final com.google.protobuf.Descriptors.EnumDescriptor
            getDescriptor() {
          return com.moosd.kitchensync.Message.Packet.BrowserPacket.getDescriptor().getEnumTypes().get(0);
        }

        private static final UriType[] VALUES = values();

        public static UriType valueOf(
            com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
          if (desc.getType() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "EnumValueDescriptor is not for this type.");
          }
          return VALUES[desc.getIndex()];
        }

        private final int index;
        private final int value;

        private UriType(int index, int value) {
          this.index = index;
          this.value = value;
        }

        // @@protoc_insertion_point(enum_scope:message.Packet.BrowserPacket.UriType)
      }

      private int bitField0_;
      public static final int TYPE_FIELD_NUMBER = 1;
      private com.moosd.kitchensync.Message.Packet.BrowserPacket.UriType type_;
      /**
       * <code>required .message.Packet.BrowserPacket.UriType type = 1;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .message.Packet.BrowserPacket.UriType type = 1;</code>
       */
      public com.moosd.kitchensync.Message.Packet.BrowserPacket.UriType getType() {
        return type_;
      }

      public static final int URI_FIELD_NUMBER = 2;
      private java.lang.Object uri_;
      /**
       * <code>required string uri = 2;</code>
       */
      public boolean hasUri() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string uri = 2;</code>
       */
      public java.lang.String getUri() {
        java.lang.Object ref = uri_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            uri_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string uri = 2;</code>
       */
      public com.google.protobuf.ByteString
          getUriBytes() {
        java.lang.Object ref = uri_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          uri_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private void initFields() {
        type_ = com.moosd.kitchensync.Message.Packet.BrowserPacket.UriType.URL;
        uri_ = "";
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        if (!hasType()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasUri()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeEnum(1, type_.getNumber());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeBytes(2, getUriBytes());
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeEnumSize(1, type_.getNumber());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(2, getUriBytes());
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static com.moosd.kitchensync.Message.Packet.BrowserPacket parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.moosd.kitchensync.Message.Packet.BrowserPacket parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.moosd.kitchensync.Message.Packet.BrowserPacket parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.moosd.kitchensync.Message.Packet.BrowserPacket parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.moosd.kitchensync.Message.Packet.BrowserPacket parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.moosd.kitchensync.Message.Packet.BrowserPacket parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static com.moosd.kitchensync.Message.Packet.BrowserPacket parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static com.moosd.kitchensync.Message.Packet.BrowserPacket parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static com.moosd.kitchensync.Message.Packet.BrowserPacket parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.moosd.kitchensync.Message.Packet.BrowserPacket parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(com.moosd.kitchensync.Message.Packet.BrowserPacket prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code message.Packet.BrowserPacket}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:message.Packet.BrowserPacket)
          com.moosd.kitchensync.Message.Packet.BrowserPacketOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.moosd.kitchensync.Message.internal_static_message_Packet_BrowserPacket_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.moosd.kitchensync.Message.internal_static_message_Packet_BrowserPacket_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.moosd.kitchensync.Message.Packet.BrowserPacket.class, com.moosd.kitchensync.Message.Packet.BrowserPacket.Builder.class);
        }

        // Construct using com.moosd.kitchensync.Message.Packet.BrowserPacket.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          type_ = com.moosd.kitchensync.Message.Packet.BrowserPacket.UriType.URL;
          bitField0_ = (bitField0_ & ~0x00000001);
          uri_ = "";
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.moosd.kitchensync.Message.internal_static_message_Packet_BrowserPacket_descriptor;
        }

        public com.moosd.kitchensync.Message.Packet.BrowserPacket getDefaultInstanceForType() {
          return com.moosd.kitchensync.Message.Packet.BrowserPacket.getDefaultInstance();
        }

        public com.moosd.kitchensync.Message.Packet.BrowserPacket build() {
          com.moosd.kitchensync.Message.Packet.BrowserPacket result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public com.moosd.kitchensync.Message.Packet.BrowserPacket buildPartial() {
          com.moosd.kitchensync.Message.Packet.BrowserPacket result = new com.moosd.kitchensync.Message.Packet.BrowserPacket(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.type_ = type_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.uri_ = uri_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.moosd.kitchensync.Message.Packet.BrowserPacket) {
            return mergeFrom((com.moosd.kitchensync.Message.Packet.BrowserPacket)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.moosd.kitchensync.Message.Packet.BrowserPacket other) {
          if (other == com.moosd.kitchensync.Message.Packet.BrowserPacket.getDefaultInstance()) return this;
          if (other.hasType()) {
            setType(other.getType());
          }
          if (other.hasUri()) {
            bitField0_ |= 0x00000002;
            uri_ = other.uri_;
            onChanged();
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          if (!hasType()) {
            
            return false;
          }
          if (!hasUri()) {
            
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.moosd.kitchensync.Message.Packet.BrowserPacket parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.moosd.kitchensync.Message.Packet.BrowserPacket) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private com.moosd.kitchensync.Message.Packet.BrowserPacket.UriType type_ = com.moosd.kitchensync.Message.Packet.BrowserPacket.UriType.URL;
        /**
         * <code>required .message.Packet.BrowserPacket.UriType type = 1;</code>
         */
        public boolean hasType() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required .message.Packet.BrowserPacket.UriType type = 1;</code>
         */
        public com.moosd.kitchensync.Message.Packet.BrowserPacket.UriType getType() {
          return type_;
        }
        /**
         * <code>required .message.Packet.BrowserPacket.UriType type = 1;</code>
         */
        public Builder setType(com.moosd.kitchensync.Message.Packet.BrowserPacket.UriType value) {
          if (value == null) {
            throw new NullPointerException();
          }
          bitField0_ |= 0x00000001;
          type_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required .message.Packet.BrowserPacket.UriType type = 1;</code>
         */
        public Builder clearType() {
          bitField0_ = (bitField0_ & ~0x00000001);
          type_ = com.moosd.kitchensync.Message.Packet.BrowserPacket.UriType.URL;
          onChanged();
          return this;
        }

        private java.lang.Object uri_ = "";
        /**
         * <code>required string uri = 2;</code>
         */
        public boolean hasUri() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>required string uri = 2;</code>
         */
        public java.lang.String getUri() {
          java.lang.Object ref = uri_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              uri_ = s;
            }
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>required string uri = 2;</code>
         */
        public com.google.protobuf.ByteString
            getUriBytes() {
          java.lang.Object ref = uri_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            uri_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string uri = 2;</code>
         */
        public Builder setUri(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          uri_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string uri = 2;</code>
         */
        public Builder clearUri() {
          bitField0_ = (bitField0_ & ~0x00000002);
          uri_ = getDefaultInstance().getUri();
          onChanged();
          return this;
        }
        /**
         * <code>required string uri = 2;</code>
         */
        public Builder setUriBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          uri_ = value;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:message.Packet.BrowserPacket)
      }

      static {
        defaultInstance = new BrowserPacket(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:message.Packet.BrowserPacket)
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>required int32 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int EP_FIELD_NUMBER = 2;
    private java.util.List<com.moosd.kitchensync.Message.Packet.EchoPacket> ep_;
    /**
     * <code>repeated .message.Packet.EchoPacket ep = 2;</code>
     */
    public java.util.List<com.moosd.kitchensync.Message.Packet.EchoPacket> getEpList() {
      return ep_;
    }
    /**
     * <code>repeated .message.Packet.EchoPacket ep = 2;</code>
     */
    public java.util.List<? extends com.moosd.kitchensync.Message.Packet.EchoPacketOrBuilder> 
        getEpOrBuilderList() {
      return ep_;
    }
    /**
     * <code>repeated .message.Packet.EchoPacket ep = 2;</code>
     */
    public int getEpCount() {
      return ep_.size();
    }
    /**
     * <code>repeated .message.Packet.EchoPacket ep = 2;</code>
     */
    public com.moosd.kitchensync.Message.Packet.EchoPacket getEp(int index) {
      return ep_.get(index);
    }
    /**
     * <code>repeated .message.Packet.EchoPacket ep = 2;</code>
     */
    public com.moosd.kitchensync.Message.Packet.EchoPacketOrBuilder getEpOrBuilder(
        int index) {
      return ep_.get(index);
    }

    public static final int BP_FIELD_NUMBER = 3;
    private java.util.List<com.moosd.kitchensync.Message.Packet.BrowserPacket> bp_;
    /**
     * <code>repeated .message.Packet.BrowserPacket bp = 3;</code>
     */
    public java.util.List<com.moosd.kitchensync.Message.Packet.BrowserPacket> getBpList() {
      return bp_;
    }
    /**
     * <code>repeated .message.Packet.BrowserPacket bp = 3;</code>
     */
    public java.util.List<? extends com.moosd.kitchensync.Message.Packet.BrowserPacketOrBuilder> 
        getBpOrBuilderList() {
      return bp_;
    }
    /**
     * <code>repeated .message.Packet.BrowserPacket bp = 3;</code>
     */
    public int getBpCount() {
      return bp_.size();
    }
    /**
     * <code>repeated .message.Packet.BrowserPacket bp = 3;</code>
     */
    public com.moosd.kitchensync.Message.Packet.BrowserPacket getBp(int index) {
      return bp_.get(index);
    }
    /**
     * <code>repeated .message.Packet.BrowserPacket bp = 3;</code>
     */
    public com.moosd.kitchensync.Message.Packet.BrowserPacketOrBuilder getBpOrBuilder(
        int index) {
      return bp_.get(index);
    }

    private void initFields() {
      id_ = 0;
      ep_ = java.util.Collections.emptyList();
      bp_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getEpCount(); i++) {
        if (!getEp(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      for (int i = 0; i < getBpCount(); i++) {
        if (!getBp(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, id_);
      }
      for (int i = 0; i < ep_.size(); i++) {
        output.writeMessage(2, ep_.get(i));
      }
      for (int i = 0; i < bp_.size(); i++) {
        output.writeMessage(3, bp_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      for (int i = 0; i < ep_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, ep_.get(i));
      }
      for (int i = 0; i < bp_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, bp_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.moosd.kitchensync.Message.Packet parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.moosd.kitchensync.Message.Packet parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.moosd.kitchensync.Message.Packet parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.moosd.kitchensync.Message.Packet parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.moosd.kitchensync.Message.Packet parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.moosd.kitchensync.Message.Packet parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.moosd.kitchensync.Message.Packet parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.moosd.kitchensync.Message.Packet parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.moosd.kitchensync.Message.Packet parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.moosd.kitchensync.Message.Packet parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.moosd.kitchensync.Message.Packet prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code message.Packet}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:message.Packet)
        com.moosd.kitchensync.Message.PacketOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.moosd.kitchensync.Message.internal_static_message_Packet_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.moosd.kitchensync.Message.internal_static_message_Packet_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.moosd.kitchensync.Message.Packet.class, com.moosd.kitchensync.Message.Packet.Builder.class);
      }

      // Construct using com.moosd.kitchensync.Message.Packet.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getEpFieldBuilder();
          getBpFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (epBuilder_ == null) {
          ep_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          epBuilder_.clear();
        }
        if (bpBuilder_ == null) {
          bp_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          bpBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.moosd.kitchensync.Message.internal_static_message_Packet_descriptor;
      }

      public com.moosd.kitchensync.Message.Packet getDefaultInstanceForType() {
        return com.moosd.kitchensync.Message.Packet.getDefaultInstance();
      }

      public com.moosd.kitchensync.Message.Packet build() {
        com.moosd.kitchensync.Message.Packet result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.moosd.kitchensync.Message.Packet buildPartial() {
        com.moosd.kitchensync.Message.Packet result = new com.moosd.kitchensync.Message.Packet(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (epBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            ep_ = java.util.Collections.unmodifiableList(ep_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.ep_ = ep_;
        } else {
          result.ep_ = epBuilder_.build();
        }
        if (bpBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            bp_ = java.util.Collections.unmodifiableList(bp_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.bp_ = bp_;
        } else {
          result.bp_ = bpBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.moosd.kitchensync.Message.Packet) {
          return mergeFrom((com.moosd.kitchensync.Message.Packet)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.moosd.kitchensync.Message.Packet other) {
        if (other == com.moosd.kitchensync.Message.Packet.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (epBuilder_ == null) {
          if (!other.ep_.isEmpty()) {
            if (ep_.isEmpty()) {
              ep_ = other.ep_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureEpIsMutable();
              ep_.addAll(other.ep_);
            }
            onChanged();
          }
        } else {
          if (!other.ep_.isEmpty()) {
            if (epBuilder_.isEmpty()) {
              epBuilder_.dispose();
              epBuilder_ = null;
              ep_ = other.ep_;
              bitField0_ = (bitField0_ & ~0x00000002);
              epBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getEpFieldBuilder() : null;
            } else {
              epBuilder_.addAllMessages(other.ep_);
            }
          }
        }
        if (bpBuilder_ == null) {
          if (!other.bp_.isEmpty()) {
            if (bp_.isEmpty()) {
              bp_ = other.bp_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureBpIsMutable();
              bp_.addAll(other.bp_);
            }
            onChanged();
          }
        } else {
          if (!other.bp_.isEmpty()) {
            if (bpBuilder_.isEmpty()) {
              bpBuilder_.dispose();
              bpBuilder_ = null;
              bp_ = other.bp_;
              bitField0_ = (bitField0_ & ~0x00000004);
              bpBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getBpFieldBuilder() : null;
            } else {
              bpBuilder_.addAllMessages(other.bp_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        for (int i = 0; i < getEpCount(); i++) {
          if (!getEp(i).isInitialized()) {
            
            return false;
          }
        }
        for (int i = 0; i < getBpCount(); i++) {
          if (!getBp(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.moosd.kitchensync.Message.Packet parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.moosd.kitchensync.Message.Packet) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>required int32 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<com.moosd.kitchensync.Message.Packet.EchoPacket> ep_ =
        java.util.Collections.emptyList();
      private void ensureEpIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          ep_ = new java.util.ArrayList<com.moosd.kitchensync.Message.Packet.EchoPacket>(ep_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.moosd.kitchensync.Message.Packet.EchoPacket, com.moosd.kitchensync.Message.Packet.EchoPacket.Builder, com.moosd.kitchensync.Message.Packet.EchoPacketOrBuilder> epBuilder_;

      /**
       * <code>repeated .message.Packet.EchoPacket ep = 2;</code>
       */
      public java.util.List<com.moosd.kitchensync.Message.Packet.EchoPacket> getEpList() {
        if (epBuilder_ == null) {
          return java.util.Collections.unmodifiableList(ep_);
        } else {
          return epBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .message.Packet.EchoPacket ep = 2;</code>
       */
      public int getEpCount() {
        if (epBuilder_ == null) {
          return ep_.size();
        } else {
          return epBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .message.Packet.EchoPacket ep = 2;</code>
       */
      public com.moosd.kitchensync.Message.Packet.EchoPacket getEp(int index) {
        if (epBuilder_ == null) {
          return ep_.get(index);
        } else {
          return epBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .message.Packet.EchoPacket ep = 2;</code>
       */
      public Builder setEp(
          int index, com.moosd.kitchensync.Message.Packet.EchoPacket value) {
        if (epBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEpIsMutable();
          ep_.set(index, value);
          onChanged();
        } else {
          epBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .message.Packet.EchoPacket ep = 2;</code>
       */
      public Builder setEp(
          int index, com.moosd.kitchensync.Message.Packet.EchoPacket.Builder builderForValue) {
        if (epBuilder_ == null) {
          ensureEpIsMutable();
          ep_.set(index, builderForValue.build());
          onChanged();
        } else {
          epBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .message.Packet.EchoPacket ep = 2;</code>
       */
      public Builder addEp(com.moosd.kitchensync.Message.Packet.EchoPacket value) {
        if (epBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEpIsMutable();
          ep_.add(value);
          onChanged();
        } else {
          epBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .message.Packet.EchoPacket ep = 2;</code>
       */
      public Builder addEp(
          int index, com.moosd.kitchensync.Message.Packet.EchoPacket value) {
        if (epBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEpIsMutable();
          ep_.add(index, value);
          onChanged();
        } else {
          epBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .message.Packet.EchoPacket ep = 2;</code>
       */
      public Builder addEp(
          com.moosd.kitchensync.Message.Packet.EchoPacket.Builder builderForValue) {
        if (epBuilder_ == null) {
          ensureEpIsMutable();
          ep_.add(builderForValue.build());
          onChanged();
        } else {
          epBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .message.Packet.EchoPacket ep = 2;</code>
       */
      public Builder addEp(
          int index, com.moosd.kitchensync.Message.Packet.EchoPacket.Builder builderForValue) {
        if (epBuilder_ == null) {
          ensureEpIsMutable();
          ep_.add(index, builderForValue.build());
          onChanged();
        } else {
          epBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .message.Packet.EchoPacket ep = 2;</code>
       */
      public Builder addAllEp(
          java.lang.Iterable<? extends com.moosd.kitchensync.Message.Packet.EchoPacket> values) {
        if (epBuilder_ == null) {
          ensureEpIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, ep_);
          onChanged();
        } else {
          epBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .message.Packet.EchoPacket ep = 2;</code>
       */
      public Builder clearEp() {
        if (epBuilder_ == null) {
          ep_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          epBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .message.Packet.EchoPacket ep = 2;</code>
       */
      public Builder removeEp(int index) {
        if (epBuilder_ == null) {
          ensureEpIsMutable();
          ep_.remove(index);
          onChanged();
        } else {
          epBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .message.Packet.EchoPacket ep = 2;</code>
       */
      public com.moosd.kitchensync.Message.Packet.EchoPacket.Builder getEpBuilder(
          int index) {
        return getEpFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .message.Packet.EchoPacket ep = 2;</code>
       */
      public com.moosd.kitchensync.Message.Packet.EchoPacketOrBuilder getEpOrBuilder(
          int index) {
        if (epBuilder_ == null) {
          return ep_.get(index);  } else {
          return epBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .message.Packet.EchoPacket ep = 2;</code>
       */
      public java.util.List<? extends com.moosd.kitchensync.Message.Packet.EchoPacketOrBuilder> 
           getEpOrBuilderList() {
        if (epBuilder_ != null) {
          return epBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(ep_);
        }
      }
      /**
       * <code>repeated .message.Packet.EchoPacket ep = 2;</code>
       */
      public com.moosd.kitchensync.Message.Packet.EchoPacket.Builder addEpBuilder() {
        return getEpFieldBuilder().addBuilder(
            com.moosd.kitchensync.Message.Packet.EchoPacket.getDefaultInstance());
      }
      /**
       * <code>repeated .message.Packet.EchoPacket ep = 2;</code>
       */
      public com.moosd.kitchensync.Message.Packet.EchoPacket.Builder addEpBuilder(
          int index) {
        return getEpFieldBuilder().addBuilder(
            index, com.moosd.kitchensync.Message.Packet.EchoPacket.getDefaultInstance());
      }
      /**
       * <code>repeated .message.Packet.EchoPacket ep = 2;</code>
       */
      public java.util.List<com.moosd.kitchensync.Message.Packet.EchoPacket.Builder> 
           getEpBuilderList() {
        return getEpFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.moosd.kitchensync.Message.Packet.EchoPacket, com.moosd.kitchensync.Message.Packet.EchoPacket.Builder, com.moosd.kitchensync.Message.Packet.EchoPacketOrBuilder> 
          getEpFieldBuilder() {
        if (epBuilder_ == null) {
          epBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.moosd.kitchensync.Message.Packet.EchoPacket, com.moosd.kitchensync.Message.Packet.EchoPacket.Builder, com.moosd.kitchensync.Message.Packet.EchoPacketOrBuilder>(
                  ep_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          ep_ = null;
        }
        return epBuilder_;
      }

      private java.util.List<com.moosd.kitchensync.Message.Packet.BrowserPacket> bp_ =
        java.util.Collections.emptyList();
      private void ensureBpIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          bp_ = new java.util.ArrayList<com.moosd.kitchensync.Message.Packet.BrowserPacket>(bp_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.moosd.kitchensync.Message.Packet.BrowserPacket, com.moosd.kitchensync.Message.Packet.BrowserPacket.Builder, com.moosd.kitchensync.Message.Packet.BrowserPacketOrBuilder> bpBuilder_;

      /**
       * <code>repeated .message.Packet.BrowserPacket bp = 3;</code>
       */
      public java.util.List<com.moosd.kitchensync.Message.Packet.BrowserPacket> getBpList() {
        if (bpBuilder_ == null) {
          return java.util.Collections.unmodifiableList(bp_);
        } else {
          return bpBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .message.Packet.BrowserPacket bp = 3;</code>
       */
      public int getBpCount() {
        if (bpBuilder_ == null) {
          return bp_.size();
        } else {
          return bpBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .message.Packet.BrowserPacket bp = 3;</code>
       */
      public com.moosd.kitchensync.Message.Packet.BrowserPacket getBp(int index) {
        if (bpBuilder_ == null) {
          return bp_.get(index);
        } else {
          return bpBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .message.Packet.BrowserPacket bp = 3;</code>
       */
      public Builder setBp(
          int index, com.moosd.kitchensync.Message.Packet.BrowserPacket value) {
        if (bpBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBpIsMutable();
          bp_.set(index, value);
          onChanged();
        } else {
          bpBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .message.Packet.BrowserPacket bp = 3;</code>
       */
      public Builder setBp(
          int index, com.moosd.kitchensync.Message.Packet.BrowserPacket.Builder builderForValue) {
        if (bpBuilder_ == null) {
          ensureBpIsMutable();
          bp_.set(index, builderForValue.build());
          onChanged();
        } else {
          bpBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .message.Packet.BrowserPacket bp = 3;</code>
       */
      public Builder addBp(com.moosd.kitchensync.Message.Packet.BrowserPacket value) {
        if (bpBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBpIsMutable();
          bp_.add(value);
          onChanged();
        } else {
          bpBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .message.Packet.BrowserPacket bp = 3;</code>
       */
      public Builder addBp(
          int index, com.moosd.kitchensync.Message.Packet.BrowserPacket value) {
        if (bpBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBpIsMutable();
          bp_.add(index, value);
          onChanged();
        } else {
          bpBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .message.Packet.BrowserPacket bp = 3;</code>
       */
      public Builder addBp(
          com.moosd.kitchensync.Message.Packet.BrowserPacket.Builder builderForValue) {
        if (bpBuilder_ == null) {
          ensureBpIsMutable();
          bp_.add(builderForValue.build());
          onChanged();
        } else {
          bpBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .message.Packet.BrowserPacket bp = 3;</code>
       */
      public Builder addBp(
          int index, com.moosd.kitchensync.Message.Packet.BrowserPacket.Builder builderForValue) {
        if (bpBuilder_ == null) {
          ensureBpIsMutable();
          bp_.add(index, builderForValue.build());
          onChanged();
        } else {
          bpBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .message.Packet.BrowserPacket bp = 3;</code>
       */
      public Builder addAllBp(
          java.lang.Iterable<? extends com.moosd.kitchensync.Message.Packet.BrowserPacket> values) {
        if (bpBuilder_ == null) {
          ensureBpIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, bp_);
          onChanged();
        } else {
          bpBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .message.Packet.BrowserPacket bp = 3;</code>
       */
      public Builder clearBp() {
        if (bpBuilder_ == null) {
          bp_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          bpBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .message.Packet.BrowserPacket bp = 3;</code>
       */
      public Builder removeBp(int index) {
        if (bpBuilder_ == null) {
          ensureBpIsMutable();
          bp_.remove(index);
          onChanged();
        } else {
          bpBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .message.Packet.BrowserPacket bp = 3;</code>
       */
      public com.moosd.kitchensync.Message.Packet.BrowserPacket.Builder getBpBuilder(
          int index) {
        return getBpFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .message.Packet.BrowserPacket bp = 3;</code>
       */
      public com.moosd.kitchensync.Message.Packet.BrowserPacketOrBuilder getBpOrBuilder(
          int index) {
        if (bpBuilder_ == null) {
          return bp_.get(index);  } else {
          return bpBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .message.Packet.BrowserPacket bp = 3;</code>
       */
      public java.util.List<? extends com.moosd.kitchensync.Message.Packet.BrowserPacketOrBuilder> 
           getBpOrBuilderList() {
        if (bpBuilder_ != null) {
          return bpBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(bp_);
        }
      }
      /**
       * <code>repeated .message.Packet.BrowserPacket bp = 3;</code>
       */
      public com.moosd.kitchensync.Message.Packet.BrowserPacket.Builder addBpBuilder() {
        return getBpFieldBuilder().addBuilder(
            com.moosd.kitchensync.Message.Packet.BrowserPacket.getDefaultInstance());
      }
      /**
       * <code>repeated .message.Packet.BrowserPacket bp = 3;</code>
       */
      public com.moosd.kitchensync.Message.Packet.BrowserPacket.Builder addBpBuilder(
          int index) {
        return getBpFieldBuilder().addBuilder(
            index, com.moosd.kitchensync.Message.Packet.BrowserPacket.getDefaultInstance());
      }
      /**
       * <code>repeated .message.Packet.BrowserPacket bp = 3;</code>
       */
      public java.util.List<com.moosd.kitchensync.Message.Packet.BrowserPacket.Builder> 
           getBpBuilderList() {
        return getBpFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.moosd.kitchensync.Message.Packet.BrowserPacket, com.moosd.kitchensync.Message.Packet.BrowserPacket.Builder, com.moosd.kitchensync.Message.Packet.BrowserPacketOrBuilder> 
          getBpFieldBuilder() {
        if (bpBuilder_ == null) {
          bpBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.moosd.kitchensync.Message.Packet.BrowserPacket, com.moosd.kitchensync.Message.Packet.BrowserPacket.Builder, com.moosd.kitchensync.Message.Packet.BrowserPacketOrBuilder>(
                  bp_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          bp_ = null;
        }
        return bpBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:message.Packet)
    }

    static {
      defaultInstance = new Packet(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:message.Packet)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_message_Packet_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_message_Packet_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_message_Packet_EchoPacket_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_message_Packet_EchoPacket_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_message_Packet_BrowserPacket_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_message_Packet_BrowserPacket_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rmessage.proto\022\007message\"\371\001\n\006Packet\022\n\n\002i" +
      "d\030\001 \002(\005\022&\n\002ep\030\002 \003(\0132\032.message.Packet.Ech" +
      "oPacket\022)\n\002bp\030\003 \003(\0132\035.message.Packet.Bro" +
      "wserPacket\032\032\n\nEchoPacket\022\014\n\004text\030\001 \002(\t\032t" +
      "\n\rBrowserPacket\0223\n\004type\030\001 \002(\0162%.message." +
      "Packet.BrowserPacket.UriType\022\013\n\003uri\030\002 \002(" +
      "\t\"!\n\007UriType\022\007\n\003URL\020\000\022\r\n\tTELEPHONE\020\001B \n\025" +
      "com.moosd.kitchensyncB\007Message"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_message_Packet_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_message_Packet_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_message_Packet_descriptor,
        new java.lang.String[] { "Id", "Ep", "Bp", });
    internal_static_message_Packet_EchoPacket_descriptor =
      internal_static_message_Packet_descriptor.getNestedTypes().get(0);
    internal_static_message_Packet_EchoPacket_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_message_Packet_EchoPacket_descriptor,
        new java.lang.String[] { "Text", });
    internal_static_message_Packet_BrowserPacket_descriptor =
      internal_static_message_Packet_descriptor.getNestedTypes().get(1);
    internal_static_message_Packet_BrowserPacket_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_message_Packet_BrowserPacket_descriptor,
        new java.lang.String[] { "Type", "Uri", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
